include_paths = [".github"]

[projects.warg_cli]
path = "warg_cli"


[projects.gnc]
path = "gnc"

[projects.perception]
path = "perception"

[projects.camera]
path = "camera"

[projects.utils]
path = "utils"

[projects.mav_comms]
path = "mav_comms"

[projects.ims]
path = "ims"

[projects.airside]
path = "airside"

[projects.gesture_control]
path = "gesture_control"

[projects.target_tracking]
path = "target_tracking"
