[projects.warg_cli]
path = "warg_cli"
[projects.SITL-Plus]
path="SITL-Plus"

[projects.kernel]
path = "kernel"

[projects.camera]
path = "camera"

[projects.utils]
path = "utils"

[projects.mav_comms]
path = "mav_comms"

[projects.ims]
path = "ims"

[projects.gesture_control]
path = "gesture_control"

[projects.target_tracking]
path = "target_tracking"