"""
Constants for the camera module.
"""
import math

CAMERA_HFOV_RAD = math.radians(80)
CAMERA_VFOV_RAD = math.radians(55)

ARDU_CAMERA_HFOV_RAD = math.radians(80)
ARDU_CAMERA_VFOV_RAD = math.radians(55)

ARDUCAM_DEFAULT_WIDTH = 1280
ARDUCAM_DEFAULT_HEIGHT = 720

OAKD_DEFAULT_WIDTH = 640
OAKD_DEFAULT_HEIGHT = 480

SIM_DEFAULT_WIDTH = 640
SIM_DEFAULT_HEIGHT = 480

ARDU_DEVICE_INDEX = 0
