[project]
name = "target_tracking"
version = "0.1.0"
description = "Target tracking module."
readme = { file = "README.md", content-type = "text/markdown" }
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.9"
dependencies = []

[project.urls]
Homepage = "https://github.com/UWARG/autonomy-monorepo/tree/main/target_tracking"
Issues = "https://github.com/UWARG/autonomy-monorepo/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[tool.hatch.build.targets.wheel]
only-include = ["src"]
sources = ["src"]
