services:
  sitl-plus:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5761:5761
      - 14550:14550
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - DISPLAY=${DISPLAY}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - SENSOR_HOST=host.docker.internal
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "/mnt/wslg:/mnt/wslg:rw" # delete on linux for docker 
      - ./logs:/app/logs
      - ./src/ardupilot/Tools/autotest/tilecache/srtm:/home/devuser/.tilecache/SRTM3:rw
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true
