[project]
name = "SITL-Plus"
version = "0.1.0"
description = "WARG's SITL archtecture"
readme = { file = "README.md", content-type = "text/markdown" }
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.9"
dependencies = [
    "black>=25.11.0",
    "numpy>=2.0.2",
    "opencv-python>=4.13.0.92",
    "pybullet>=3.2.7",
    "pylint>=3.3.9",
    "pymavlink>=2.4.49",
    "rerun-sdk>=0.26.2",
    "scipy>=1.13.1",
]

[project.urls]
Homepage = "https://github.com/UWARG/autonomy-monorepo/tree/main/SITL-Plus"
Issues = "https://github.com/UWARG/autonomy-monorepo/issues"

[project.optional-dependencies]
dev = ["pytest>=8.0.0", "ruff>=0.8.0"]

[project.scripts]
sitl_plus = "main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[tool.hatch.build.targets.wheel]
only-include = ["src"]
sources = ["src"]

[tool.black]
line-length = 88
extend-exclude = "ardupilot"

[tool.pylint.main]
ignore = ["ardupilot", ".venv"]
ignore-paths = [
    "^.*ardupilot(/|$).*",
    "^.*\\.venv(/|$).*",
]
extension-pkg-allow-list = ["pybullet", "cv2"]
max-line-length = 88
py-version = "3.11"

[tool.pylint.messages_control]
disable = [
    "duplicate-code",
    "import-error",
    "too-many-instance-attributes",
    "too-many-arguments",
    "too-many-positional-arguments",
    "too-many-locals",
    "too-many-branches",
    "too-many-statements",
    "too-few-public-methods",
    "global-statement",
    "global-variable-not-assigned",
]

[tool.pylint.basic]
good-names = ["R", "L", "i", "j", "k", "x", "y", "z", "w", "id"]
good-names-rgxs = ["^_.*", ".*_AP$", ".*_SITL_frame$"]

[tool.pylint.typecheck]
generated-members = ["cv2.*"]
