name = "sitl-plus"
description = "WARG's SITL archtecture"

depends_on = []

[commands]
setup = "uv sync"
build = "uv build"
test = "uv run --extra dev pytest"
run = "uv run python -m main"
groundside="uv run python tests/integration_tests/camera_test.py"
airside="uv run python tests/integration_tests/mavlink_test.py"
lint = "uv run --extra dev ruff check ."

[ci]
pr = ["lint", "test"]
main = ["test", "build"]
