services:
  airside-prec:
    build:
      context: ..
      dockerfile: airside_prec/docker/Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    image: uwarg/airside-prec:0.1.3
    environment:
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
    command: ros2 launch engine engine.launch.py
    restart: unless-stopped
    volumes:
      - ./src:/ros_ws/src
      - ..:/monorepo
    devices:
      - /dev/video0:/dev/video0
      - /dev/ttyAMA0:/dev/ttyAMA0
    privileged: true

