services:
  prec-non-optimal:
    build:
      context: ..
      dockerfile: prec_non_optimal/docker/Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    image: uwarg/prec-non-optimal:0.1.0
    environment:
      - ${ROS_DOMAIN_ID:-0}
    command: ros2 launch engine engine.launch.py
    restart: unless-stopped
    volumes:
      - ./src:/ros_ws/src
      - ..:/monorepo
    devices:
      - /dev/video0:/dev/video0
      - /dev/ttyAMA0:/dev/ttyAMA0
    privileged: true

