# Lap waypoints. `home` orients the waypoints
# and is the returning location at the end
# of the mission.
home:
  lat: 43.4338
  lon: -80.57732
  alt: 10

waypoints:
  - lat: 43.43388
    lon: -80.5776
    alt: 10
  - lat: 43.43403
    lon: -80.57797
    alt: 10
  - lat: 43.43393
    lon: -80.57801
    alt: 10
