from __future__ import annotations

import getpass
import shutil
import string
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

from errors import StartupError
from registry import Registry

SYNC_UNIT = "warg-startup.service"
UNIT_MARKER = "# Generated by warg startup"
LINGER_DIR = Path("/var/lib/systemd/linger")

_UNIT_NAME_CHARS = frozenset(string.ascii_letters + string.digits + ":_.-")
_BARE_EXEC_ARG_CHARS = frozenset(string.ascii_letters + string.digits + "_+-=.,:/@")


@dataclass(frozen=True)
class StartupEntry:
    project: str
    command: str
    restart: str

    @property
    def unit_name(self) -> str:
        project = _unit_name_part(self.project)
        command = _unit_name_part(self.command)
        return f"warg-{project}-{command}.service"


@dataclass
class SyncResult:
    added: list[str] = field(default_factory=list)
    updated: list[str] = field(default_factory=list)
    removed: list[str] = field(default_factory=list)
    unchanged: list[str] = field(default_factory=list)


class SystemdUser:
    def __init__(self, unit_dir: Path | None = None):
        # The user manager reads ~/.config/systemd/user at boot regardless of
        # any XDG_CONFIG_HOME a shell exports, so units always go there.
        self.unit_dir = unit_dir or Path.home() / ".config" / "systemd" / "user"

    def ensure_available(self) -> None:
        if not sys.platform.startswith("linux"):
            raise StartupError(
                "Startup commands run as systemd services, so they need Linux "
                f"(this machine is '{sys.platform}')."
            )
        if shutil.which("systemctl") is None:
            raise StartupError(
                "systemctl was not found. Startup commands need a Linux system "
                "that runs systemd, such as Raspberry Pi OS."
            )
        result = self._systemctl("show-environment", check=False)
        if result.returncode != 0:
            raise StartupError(
                f"Could not reach the systemd user manager ({_output(result)}). "
                "Run warg as your normal user, not with sudo."
            )

    def is_available(self) -> bool:
        try:
            self.ensure_available()
        except StartupError:
            return False
        return True

    def generated_units(self) -> list[str]:
        if not self.unit_dir.is_dir():
            return []
        return sorted(
            path.name
            for path in self.unit_dir.glob("warg-*.service")
            if path.is_file() and path.read_text().startswith(UNIT_MARKER)
        )

    def read_unit(self, name: str) -> str | None:
        path = self.unit_dir / name
        if not path.is_file():
            return None
        content = path.read_text()
        if not content.startswith(UNIT_MARKER):
            raise StartupError(
                f"{path} already exists and was not generated by warg. Move it "
                "aside, then rerun."
            )
        return content

    def write_unit(self, name: str, content: str) -> None:
        self.unit_dir.mkdir(parents=True, exist_ok=True)
        (self.unit_dir / name).write_text(content)

    def remove_unit(self, name: str) -> None:
        (self.unit_dir / name).unlink(missing_ok=True)

    def unit_state(self, name: str) -> str:
        if not (self.unit_dir / name).is_file():
            return "not installed"
        result = self._systemctl("is-active", name, check=False)
        return result.stdout.strip() or "unknown"

    def daemon_reload(self) -> None:
        self._systemctl("daemon-reload")

    def enable(self, names: list[str]) -> None:
        self._systemctl("enable", *names)

    def disable(self, names: list[str]) -> None:
        self._systemctl("disable", "--now", *names, check=False)

    def start(self, names: list[str]) -> None:
        # --no-block matters at boot: units are ordered after the sync unit,
        # so waiting on them from inside it would deadlock.
        self._systemctl("start", "--no-block", *names)

    def try_restart(self, names: list[str]) -> None:
        self._systemctl("try-restart", "--no-block", *names)

    def linger_enabled(self) -> bool:
        return (LINGER_DIR / getpass.getuser()).exists()

    def enable_linger(self) -> bool:
        try:
            result = subprocess.run(
                ["loginctl", "--no-ask-password", "enable-linger", getpass.getuser()],
                check=False,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )
        except FileNotFoundError:
            return False
        return result.returncode == 0

    def _systemctl(
        self, *args: str, check: bool = True
    ) -> subprocess.CompletedProcess[str]:
        result = subprocess.run(
            ["systemctl", "--user", *args],
            check=False,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        if check and result.returncode != 0:
            command = " ".join(["systemctl", "--user", *args])
            raise StartupError(f"{command} failed: {_output(result)}")
        return result


def startup_entries(registry: Registry) -> list[StartupEntry]:
    entries: dict[str, StartupEntry] = {}
    for project in registry.projects.values():
        for command in project.startup.commands:
            entry = StartupEntry(project.name, command, project.startup.restart)
            if entry.unit_name in entries:
                other = entries[entry.unit_name]
                raise StartupError(
                    f"Startup commands '{other.project} {other.command}' and "
                    f"'{entry.project} {entry.command}' would both install "
                    f"{entry.unit_name}. Rename one of the commands."
                )
            entries[entry.unit_name] = entry
    return list(entries.values())


def render_units(registry: Registry, *, warg: str, path_env: str) -> dict[str, str]:
    return {
        entry.unit_name: render_command_unit(
            entry, root=registry.root, warg=warg, path_env=path_env
        )
        for entry in startup_entries(registry)
    }


def render_command_unit(
    entry: StartupEntry, *, root: Path, warg: str, path_env: str
) -> str:
    return _render_unit(
        f"WARG {entry.project}: {entry.command}",
        unit=[f"After={SYNC_UNIT}"],
        service=[
            "Type=simple",
            f"WorkingDirectory={_escape_specifiers(str(root))}",
            _environment("PATH", path_env),
            _environment("PYTHONUNBUFFERED", "1"),
            _exec_start(warg, "run", entry.project, entry.command),
            f"Restart={entry.restart}",
            "RestartSec=5",
        ],
    )


def render_sync_unit(*, root: Path, warg: str, path_env: str) -> str:
    return _render_unit(
        "Sync WARG startup services from warg.toml manifests",
        unit=[],
        service=[
            "Type=oneshot",
            f"WorkingDirectory={_escape_specifiers(str(root))}",
            _environment("PATH", path_env),
            _exec_start(warg, "startup", "sync"),
        ],
    )


def install_sync_unit(systemd: SystemdUser, content: str) -> None:
    if systemd.read_unit(SYNC_UNIT) != content:
        systemd.write_unit(SYNC_UNIT, content)
        systemd.daemon_reload()
    systemd.enable([SYNC_UNIT])


def sync_units(systemd: SystemdUser, units: dict[str, str]) -> SyncResult:
    result = SyncResult()
    for name, content in units.items():
        current = systemd.read_unit(name)
        if current == content:
            result.unchanged.append(name)
        elif current is None:
            result.added.append(name)
        else:
            result.updated.append(name)

    result.removed = [
        name
        for name in systemd.generated_units()
        if name != SYNC_UNIT and name not in units
    ]
    if result.removed:
        systemd.disable(result.removed)
        for name in result.removed:
            systemd.remove_unit(name)

    for name in [*result.added, *result.updated]:
        systemd.write_unit(name, units[name])

    if result.added or result.updated or result.removed:
        systemd.daemon_reload()
    if units:
        systemd.enable(list(units))
        if result.updated:
            systemd.try_restart(result.updated)
        systemd.start(list(units))
    return result


def uninstall_units(systemd: SystemdUser) -> list[str]:
    names = systemd.generated_units()
    if names:
        systemd.disable(names)
        for name in names:
            systemd.remove_unit(name)
        systemd.daemon_reload()
    return names


def find_warg_executable() -> str:
    invoked = Path(sys.argv[0])
    if invoked.name == "warg" and invoked.is_file():
        return str(invoked.absolute())
    found = shutil.which("warg")
    if found is None:
        raise StartupError(
            "Could not find the warg executable for services to run. Install it "
            "with 'uv tool install warg-cli'."
        )
    return str(Path(found).absolute())


def _render_unit(description: str, *, unit: list[str], service: list[str]) -> str:
    lines = [
        f"{UNIT_MARKER}. Edit warg.toml instead of this file.",
        "",
        "[Unit]",
        f"Description={_escape_specifiers(description)}",
        *unit,
        "",
        "[Service]",
        *service,
        "",
        "[Install]",
        "WantedBy=default.target",
    ]
    return "\n".join(lines) + "\n"


def _exec_start(*args: str) -> str:
    return "ExecStart=" + " ".join(_exec_arg(arg) for arg in args)


def _exec_arg(value: str) -> str:
    value = _escape_specifiers(value).replace("$", "$$")
    if value and all(char in _BARE_EXEC_ARG_CHARS for char in value):
        return value
    return _quote(value)


def _environment(name: str, value: str) -> str:
    return "Environment=" + _quote(_escape_specifiers(f"{name}={value}"))


def _quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _escape_specifiers(value: str) -> str:
    return value.replace("%", "%%")


def _unit_name_part(value: str) -> str:
    return "".join(char if char in _UNIT_NAME_CHARS else "_" for char in value)


def _output(result: subprocess.CompletedProcess[str]) -> str:
    return (
        result.stderr.strip()
        or result.stdout.strip()
        or f"exit code {result.returncode}"
    )
