from __future__ import annotations

import getpass
import shutil
import string
import subprocess
import sys
from collections.abc import Iterable
from dataclasses import dataclass, field
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover
    import tomli as tomllib  # type: ignore[no-redef]

from errors import StartupError
from registry import Registry

UNIT_MARKER = "# Generated by warg startup"
LINGER_DIR = Path("/var/lib/systemd/linger")
SYSTEM_PATH = "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
RESTART_DELAY_SECONDS = 5
# A service that keeps failing is restarted at most this many times within the
# window, then left in the 'failed' state instead of retrying forever.
RESTART_LIMIT_BURST = 5
RESTART_LIMIT_WINDOW_SECONDS = 60

_UNIT_NAME_CHARS = frozenset(string.ascii_letters + string.digits + ":_.-")
_BARE_EXEC_ARG_CHARS = frozenset(string.ascii_letters + string.digits + "_+-=.,:/@")
_ENV_NAME_START_CHARS = frozenset(string.ascii_letters + "_")
_ENV_NAME_CHARS = _ENV_NAME_START_CHARS | frozenset(string.digits)


@dataclass(frozen=True)
class MachineConfig:
    """Per-machine startup settings, kept outside the repo."""

    projects: tuple[str, ...] = field(default_factory=tuple)
    environment: dict[str, str] = field(default_factory=dict)


@dataclass(frozen=True)
class StartupEntry:
    project: str
    command: str
    restart: str

    @property
    def unit_name(self) -> str:
        project = _unit_name_part(self.project)
        command = _unit_name_part(self.command)
        return f"warg-{project}-{command}.service"


@dataclass
class SyncResult:
    added: list[str] = field(default_factory=list)
    updated: list[str] = field(default_factory=list)
    removed: list[str] = field(default_factory=list)
    unchanged: list[str] = field(default_factory=list)


class SystemdUser:
    def __init__(self, unit_dir: Path | None = None):
        # The user manager reads ~/.config/systemd/user at boot regardless of
        # any XDG_CONFIG_HOME a shell exports, so units always go there.
        self.unit_dir = unit_dir or Path.home() / ".config" / "systemd" / "user"

    def ensure_available(self) -> None:
        if not sys.platform.startswith("linux"):
            raise StartupError(
                "Startup commands run as systemd services, so they need Linux "
                f"(this machine is '{sys.platform}')."
            )
        if shutil.which("systemctl") is None:
            raise StartupError(
                "systemctl was not found. Startup commands need a Linux system "
                "that runs systemd, such as Raspberry Pi OS."
            )
        result = self._systemctl("show-environment", check=False)
        if result.returncode != 0:
            raise StartupError(
                f"Could not reach the systemd user manager ({_output(result)}). "
                "Run warg as your normal user, not with sudo."
            )

    def is_available(self) -> bool:
        try:
            self.ensure_available()
        except StartupError:
            return False
        return True

    def generated_units(self) -> list[str]:
        # Units are named after the project and command only, so every clone
        # on this machine shares them: syncing from a second clone replaces the
        # first clone's services. Startup commands assume one clone per user.
        if not self.unit_dir.is_dir():
            return []
        return sorted(
            path.name
            for path in self.unit_dir.glob("warg-*.service")
            if path.is_file() and path.read_text().startswith(UNIT_MARKER)
        )

    def read_unit(self, name: str) -> str | None:
        path = self.unit_dir / name
        if not path.is_file():
            return None
        content = path.read_text()
        if not content.startswith(UNIT_MARKER):
            raise StartupError(
                f"{path} already exists and was not generated by warg. Move it "
                "aside, then rerun."
            )
        return content

    def write_unit(self, name: str, content: str) -> None:
        self.unit_dir.mkdir(parents=True, exist_ok=True)
        (self.unit_dir / name).write_text(content)

    def remove_unit(self, name: str) -> None:
        (self.unit_dir / name).unlink(missing_ok=True)

    def unit_state(self, name: str) -> str:
        if not (self.unit_dir / name).is_file():
            return "not installed"
        result = self._systemctl("is-active", name, check=False)
        return result.stdout.strip() or "unknown"

    def daemon_reload(self) -> None:
        self._systemctl("daemon-reload")

    def enable(self, names: list[str]) -> None:
        self._systemctl("enable", *names)

    def disable(self, names: list[str]) -> None:
        self._systemctl("disable", "--now", *names, check=False)

    def start(self, names: list[str]) -> None:
        self._systemctl("start", "--no-block", *names)

    def try_restart(self, names: list[str]) -> None:
        self._systemctl("try-restart", "--no-block", *names)

    def linger_enabled(self) -> bool:
        return (LINGER_DIR / getpass.getuser()).exists()

    def enable_linger(self) -> bool:
        try:
            result = subprocess.run(
                ["loginctl", "--no-ask-password", "enable-linger", getpass.getuser()],
                check=False,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )
        except FileNotFoundError:
            return False
        return result.returncode == 0

    def _systemctl(
        self, *args: str, check: bool = True
    ) -> subprocess.CompletedProcess[str]:
        result = subprocess.run(
            ["systemctl", "--user", *args],
            check=False,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        if check and result.returncode != 0:
            command = " ".join(["systemctl", "--user", *args])
            raise StartupError(f"{command} failed: {_output(result)}")
        return result


def machine_config_path() -> Path:
    return Path.home() / ".config" / "warg" / "startup.toml"


def load_machine_config(
    path: Path | None = None, *, missing_ok: bool = False
) -> MachineConfig:
    path = path or machine_config_path()
    if not path.is_file():
        if missing_ok:
            return MachineConfig()
        raise StartupError(
            f"Missing startup config: {path}. Create it and list the projects "
            "whose startup commands this machine should run, for example:\n"
            '  projects = ["gesture_control"]'
        )

    try:
        with path.open("rb") as file:
            data = tomllib.load(file)
    except tomllib.TOMLDecodeError as error:
        raise StartupError(f"{path}: {error}") from error

    unknown = sorted(set(data) - {"projects", "environment"})
    if unknown:
        raise StartupError(
            f"{path}: unknown key(s): {', '.join(unknown)}. Expected 'projects' "
            "and optionally '[environment]'."
        )

    projects = data.get("projects", [])
    if not isinstance(projects, list) or not all(
        isinstance(item, str) and item for item in projects
    ):
        raise StartupError(f"{path}: 'projects' must be a list of project names.")

    environment = data.get("environment", {})
    if not isinstance(environment, dict) or not all(
        isinstance(value, str) for value in environment.values()
    ):
        raise StartupError(f"{path}: '[environment]' must map names to strings.")
    for name in environment:
        if not _is_env_name(name):
            raise StartupError(
                f"{path}: '{name}' is not a valid environment variable name."
            )

    return MachineConfig(
        projects=tuple(dict.fromkeys(projects)), environment=dict(environment)
    )


def service_environment(config: MachineConfig) -> dict[str, str]:
    # PATH is built from fixed locations rather than copied from the calling
    # shell, so an active venv or other shell state never leaks into services.
    # Anything else a command needs is declared in the machine config.
    return {
        "PATH": f"{Path.home() / '.local' / 'bin'}:{SYSTEM_PATH}",
        "PYTHONUNBUFFERED": "1",
        **config.environment,
    }


def startup_entries(registry: Registry, projects: Iterable[str]) -> list[StartupEntry]:
    entries: dict[str, StartupEntry] = {}
    for name in projects:
        project = registry.get(name)
        for command in project.startup.commands:
            entry = StartupEntry(project.name, command, project.startup.restart)
            if entry.unit_name in entries:
                other = entries[entry.unit_name]
                raise StartupError(
                    f"Startup commands '{other.project} {other.command}' and "
                    f"'{entry.project} {entry.command}' would both install "
                    f"{entry.unit_name}. Rename one of the commands."
                )
            entries[entry.unit_name] = entry
    return list(entries.values())


def render_units(
    registry: Registry, config: MachineConfig, *, warg: str
) -> dict[str, str]:
    environment = service_environment(config)
    return {
        entry.unit_name: render_command_unit(
            entry, root=registry.root, warg=warg, environment=environment
        )
        for entry in startup_entries(registry, config.projects)
    }


def render_command_unit(
    entry: StartupEntry, *, root: Path, warg: str, environment: dict[str, str]
) -> str:
    unit: list[str] = []
    service = [
        "Type=simple",
        f"WorkingDirectory={_escape_specifiers(str(root))}",
        *(_environment(name, value) for name, value in environment.items()),
        _exec_start(warg, "run", entry.project, entry.command),
        f"Restart={entry.restart}",
    ]
    if entry.restart != "no":
        unit += [
            f"StartLimitIntervalSec={RESTART_LIMIT_WINDOW_SECONDS}",
            f"StartLimitBurst={RESTART_LIMIT_BURST}",
        ]
        service.append(f"RestartSec={RESTART_DELAY_SECONDS}")
    return _render_unit(
        f"WARG {entry.project}: {entry.command}", unit=unit, service=service
    )


def sync_units(systemd: SystemdUser, units: dict[str, str]) -> SyncResult:
    result = SyncResult()
    for name, content in units.items():
        current = systemd.read_unit(name)
        if current == content:
            result.unchanged.append(name)
        elif current is None:
            result.added.append(name)
        else:
            result.updated.append(name)

    result.removed = [name for name in systemd.generated_units() if name not in units]
    if result.removed:
        systemd.disable(result.removed)
        for name in result.removed:
            systemd.remove_unit(name)

    for name in [*result.added, *result.updated]:
        systemd.write_unit(name, units[name])

    if result.added or result.updated or result.removed:
        systemd.daemon_reload()
    if units:
        systemd.enable(list(units))
        if result.updated:
            systemd.try_restart(result.updated)
        systemd.start(list(units))
    return result


def uninstall_units(systemd: SystemdUser) -> list[str]:
    names = systemd.generated_units()
    if names:
        systemd.disable(names)
        for name in names:
            systemd.remove_unit(name)
        systemd.daemon_reload()
    return names


def find_warg_executable() -> str:
    invoked = Path(sys.argv[0])
    if invoked.name == "warg" and invoked.is_file():
        return str(invoked.absolute())
    found = shutil.which("warg")
    if found is None:
        raise StartupError(
            "Could not find the warg executable for services to run. Install it "
            "with 'uv tool install warg-cli'."
        )
    return str(Path(found).absolute())


def _render_unit(description: str, *, unit: list[str], service: list[str]) -> str:
    lines = [
        f"{UNIT_MARKER}. Rerun 'warg startup sync' instead of editing this file.",
        "",
        "[Unit]",
        f"Description={_escape_specifiers(description)}",
        *unit,
        "",
        "[Service]",
        *service,
        "",
        "[Install]",
        "WantedBy=default.target",
    ]
    return "\n".join(lines) + "\n"


def _exec_start(*args: str) -> str:
    return "ExecStart=" + " ".join(_exec_arg(arg) for arg in args)


def _exec_arg(value: str) -> str:
    value = _escape_specifiers(value).replace("$", "$$")
    if value and all(char in _BARE_EXEC_ARG_CHARS for char in value):
        return value
    return _quote(value)


def _environment(name: str, value: str) -> str:
    return "Environment=" + _quote(_escape_specifiers(f"{name}={value}"))


def _is_env_name(name: str) -> bool:
    return (
        bool(name)
        and name[0] in _ENV_NAME_START_CHARS
        and all(char in _ENV_NAME_CHARS for char in name)
    )


def _quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _escape_specifiers(value: str) -> str:
    return value.replace("%", "%%")


def _unit_name_part(value: str) -> str:
    return "".join(char if char in _UNIT_NAME_CHARS else "_" for char in value)


def _output(result: subprocess.CompletedProcess[str]) -> str:
    return (
        result.stderr.strip()
        or result.stdout.strip()
        or f"exit code {result.returncode}"
    )
